### ISSUE TITLE
能不能详细介绍一下事件处理流程?

### ISSUE THREAD

**Issue by cos12a** [FlandreUNX/uModbusMaster#3]
能不能详细介绍一下事件处理流程?
另，Time时器T3.5 和t35是什么关系？定时值是怎么得来的？
50uS和 定下面定时器初始化值是什么关系？
TIM_TimeBaseStructure.TIM_Period = mbm_Timer.t35_Value;
 TIM_TimeBaseStructure.TIM_Prescaler = (uint16_t)TIME_PER_50US_PSC;

多谢!

**Comment by FlandreUNX** [comment]
T3.5=t35 只是没有写成3t5

以50us作为一个时基
TIM_Prescaler = (uint16_t)TIME_PER_50US_PSC; 是设置定时器50us计数一次所需要的PSC值
.t35_Value的值请看mbm.c里面的uMBM_CoreInit()的timer初始化过程

事件处理流程是事件驱动,
收到字符串(事件)
并等待接收完毕后(事件)
处理数据(事件)
分发数据(事件)
写入缓冲(事件)
