### ISSUE TITLE
关于查询同步锁timeout超时是在哪里处理?如何处理的?

### ISSUE THREAD

**Issue by cos12a** [FlandreUNX/uModbusMaster#5]
如下没有发现：查询同步锁timeout超时是在哪里处理?是如何处理的?
bool pMBM_SemaphoreWait(uint32_t timeout) {
  osStatus_t val =  osSemaphoreAcquire(mbm_Sem_ID, timeout);
  if (val == osOK) {
    return true;
  }
  else {
    return false;
  }
}

/* 查询同步锁 */
if (!dev->event->pMBM_SemaphoreWait(timeout)) {
return MBM_ERR_BUSY;
}

**Comment by FlandreUNX** [comment]
dev->event->pMBM_SemaphoreWait(timeout) 超时直接返回MBM_ERR_BUSY

bool pMBM_SemaphoreWait(uint32_t timeout)就是获取互斥锁,获取成功就返回true,获取失败或者超时就返回false

**Comment by cos12a** [comment]
如果在查询时没有超时，在锁定执行过程中未释放之前发生TimeOut溢出事件要如何处理呢?
如下：
  /* 查询同步锁 */
  if (!dev->event->pMBM_SemaphoreWait(timeout)) {
    return MBM_ERR_BUSY;
  }
  .....在这之间发生TimeOut 溢出事件？如何处理的。。。

  dev->event->pMBM_SemaphoreRelease();
  
  return uMBM_UserEvent2ErrorCode(event);

**Comment by FlandreUNX** [comment]
//查询锁,能锁就锁
if (!dev->event->pMBM_SemaphoreWait(timeout)) {
return MBM_ERR_BUSY;
}
...........................
{
这中间已经锁住了
}
...........................
//查询锁,能解锁就解锁
dev->event->pMBM_SemaphoreRelease();


请查看RTX5的 API

**Comment by FlandreUNX** [comment]
溢出时间在poll循环里面处理 这个pMBM_SemaphoreRelease是锁住对用户api的,modbus timeout事件 在后台处理

**Comment by cos12a** [comment]
谢谢!明白了.
